# Generated by Django 3.2 on 2021-04-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterField(
            model_name='bookings',
            name='content',
            field=models.TextField(blank=True, verbose_name='Посетитель'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Подтверждение брони'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Столик'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='updated_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата посещения'),
        ),
    ]
