# Generated by Django 3.2 on 2021-04-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookings_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookings',
            table='bookings_bookings',
        ),
    ]
